### ISSUE TITLE
First paragraph is always unnumbered 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-mpfa#8]
I thought this was their bug, but they say this is intentional — all documents published by the HK government do not have number 1 and it is always the Intro. 

It’s a feature, not a bug. Goodness me.

**Comment by ronaldtse** [comment]
And the paragraph following it always starts with 2.

**Comment by opoudjis** [comment]
Please tell me which of the current documents need to be changed, because I'm not convinced there is a straightforward pattern here at all. The request is meaningless for the _Compliance Standards For Trustees: Supervision of MPF Intermediaries_, for example.

And I did not implement paragraph numbering in MPFD, only in Unece.

**Comment by ronaldtse** [comment]
Sample attached. This is only for the Guidelines.

[V_2.pdf](https://github.com/riboseinc/metanorma-mpfd/files/2540606/V_2.pdf)

**Comment by opoudjis** [comment]
So the "1." does not appear, but the blank space does.
